version: '3'
services:
    keycloak-database:
        container_name: keycloak-database
        image: postgres:9.5
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=keycloak
        volumes:
        - ./data/postgresql:/var/lib/postgresql/data
    keycloak:
        container_name: keycloak
        image: jboss/keycloak
        depends_on:
        - keycloak-database      
        ports:
        - "8080:8080"
        environment:
        - KEYCLOAK_USER=keycloak
        - KEYCLOAK_PASSWORD=keycloak
        - DB_ADDR=keycloak-database
        - DB_PORT=5432
        - DB_DATABASE=keycloak
        - DB_USER=postgres
        - DB_PASSWORD=postgres